### ISSUE TITLE
where is /_includes/social_media_share_url.html

### ISSUE THREAD

**Issue by mashoushan1989** [github/personal-website#127]
I can not find this file</_includes/social_media_share_url.html> in the repository that mentioned in th readme.md file.

**Comment by BaileyJM02** [comment]
I believe it was removed due to it not being needed. The files should be `_config.yml` and `_data/social_media.yml`. If you wish to customise your social handles, you need to add something like so to `_data/social_media.yml`:

```yml
socialname:
  name: "Social Name"
  profile_url_prefix: https://social-website.com/
  icon_svg: '<svg>SVG Image</svg>'
```
and then add something like so to `_config.yml`:
```yml
social_media:
  socialname:  username
```
