### ISSUE TITLE
Exclude forks except

### ISSUE THREAD

**Issue by artemgurzhii** [github/personal-website#192]
I have a lot of forks that I would like to exclude from my projects list but are still a few of them which I would like to include. I haven't found any way to achieve this.

I see 2 possible API's for this

**First option:**
```yml
projects:
  exclude:
    forks: true
    except:
      - my_awesome_fork
```

**Second option:**
```yml
projects:
  exclude:
    forks: true
  include:
    - my_greatest_fork
```

I prefer second option more because of the less nesting, but they both are still intuitively clear for me.
