### ISSUE TITLE
Social links?

### ISSUE THREAD

**Issue by benhalpern** [github/personal-website#40]
I think it probably makes sense to have social icons on these pages with links to the user's various profiles/identities.

The left sidebar seems to fit as being the place to display configured icons.

**Comment by kunicmarko20** [comment]
Another useful thing would be share to social networks on blog page

**Comment by PatMyron** [comment]
Would https://fontawesome.com/ help support more social links?

I used it for https://patmyron.com/ and it was really easy to use: https://github.com/PatMyron/patmyron.github.io/blob/fb86739dbcd16b9a1b3ee58302b5a24f5ebfe83a/header.html

It'd be awesome to support email, Stack Overflow, Behance, etc

**Comment by brandonrosage** [comment]
Unless you object, I think the current convention (which I'll document in the repo) is pretty efficient:

1. Edit the [`_data/social_media.yml`](https://github.com/github/personal-website/blob/master/_data/social_media.yml) file
2. Add the desired service using the pattern demonstrated in the file:

For example:
```
youtube:
  name: YouTube
  profile_url_prefix: https://www.youtube.com/
  icon_svg: '<svg height="20" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 19.17 13.6"><path d="M18.77 2.13A2.4 2.4 0 0 0 17.09.42C15.59 0 9.58 0 9.58 0a57.55 57.55 0 0 0-7.5.4A2.49 2.49 0 0 0 .39 2.13 26.27 26.27 0 0 0 0 6.8a26.15 26.15 0 0 0 .39 4.67 2.43 2.43 0 0 0 1.69 1.71c1.52.42 7.5.42 7.5.42a57.69 57.69 0 0 0 7.51-.4 2.4 2.4 0 0 0 1.68-1.71 25.63 25.63 0 0 0 .4-4.67 24 24 0 0 0-.4-4.69zM7.67 9.71V3.89l5 2.91z" fill="#959da5"/></svg>'
```

3. Enable the service by defining in your [`_config.yml`](https://github.com/github/personal-website/blob/master/_config.yml) the username you identify with that service.

For example:

```
social_media:
  twitter: your_username
  youtube: your_username
```

This allows us to organize all the necessary data for each service and contain the visual assets all in one place, with no additional overhead.
